### ISSUE TITLE
v0.3.17 thrown generic type issue

### ISSUE THREAD

**Issue by THenryT** [bergben/ng2-image-gallery#10]
ERROR in ../node_modules/ng2-image-gallery/dist/src/ng2-image-gallery-displacer.component.d.ts (3,55): Generic type 'TemplatePortal<C>' requires 1 type argument(s).

**Comment by otachkin** [comment]
TemplatePortal is a generic type. The code is need to be changed to
`TemplatePortal<any>`
in /node_modules/ng2-image-gallery/dist/src/ng2-image-gallery-displacer.component.d.ts (3,55)
i'am add a pull request #11

**Comment by bergben** [comment]
Thank you @otachkin , merged your PR.
