### ISSUE TITLE
Generic type 'TemplatePortal<C>' requires 1 type argument(s).

### ISSUE THREAD

**Issue by shoaibakhtar26** [bergben/ng2-image-gallery#12]
am using npm as package manager in my angular project. Want to use ng-2 image gallery in my project. I added `ng2-image-gallery` version 0.3.17 and `@angular/material` version 2.0.0-beta.7 as dependencies in `package.json`.  Installed these dependencies by running `npm install`. When i try to start my project by running `npm start` then it gives error

> ERROR in node_modules/ng2-image-gallery/dist/src/ng2-image-gallery-displacer.component.d.ts (3,55): Generic type 'TemplatePortal<C>' requires 1 type argument(s).

**Comment by bergben** [comment]
Hey @shoaibakhtar26 . Please try again with version 0.3.18 :)

**Comment by shoaibakhtar26** [comment]
@bergben thanks a lot. using `ng-2-image-gallery` version 0.3.18 solved this issue
