### ISSUE TITLE
Image modal close button not working

### ISSUE THREAD

**Issue by PeterOsifeso** [bergben/ng2-image-gallery#4]
I have been able to implement your gallery modal component and I really do like the design but I have a problem with the close button, somehow all other buttons, next, previous and thumbnail buttons work but the close button does not work. I need help

**Comment by bergben** [comment]
Hi @PeterOsifeso,

I will need further details about your issue. Best would be if you could provide a plnkr. You can use the demo plnkr: http://plnkr.co/edit/Qyg5m7XsiKCBpqa6I4ku?p=preview
