### ISSUE TITLE
Release with NG4

### ISSUE THREAD

**Issue by krzysztof-grzelak** [bergben/ng2-image-gallery#5]
When you plan create next release supported NG4?

**Comment by bergben** [comment]
Hey @grzelix.
As you can see in the demo plnkr: http://run.plnkr.co/zhR6wAMZnx3gCNOY/ the gallery works just fine with ng4 :)

**Comment by krzysztof-grzelak** [comment]
Yes, I see that you added changes related to NG4. But my question is about formal NPM package. If I decide use your project, I would like do it in standard way by adding dependency via NPM. If it is your pet project and You do not plan any more formal releases, that's also fine. 

Cheers.

**Comment by bergben** [comment]
Oh right @grzelix  I see. I will do that ASAP by tomorrow

**Comment by bergben** [comment]
I have just released version 0.3.17 @grzelix
